-- CreateEnum
CREATE TYPE "SimRole" AS ENUM ('ENDURANCE_DRIVER', 'SPRINT_DRIVER', 'OVAL_DRIVER', 'RALLY_DRIVER', 'DRIFT_DRIVER', 'TIME_ATTACK_DRIVER', 'RACE_ENGINEER', 'SETUP_ENGINEER', 'STRATEGIST', 'SPOTTER', 'DRIVER_COACH', 'TEAM_PRINCIPAL', 'LEAGUE_ADMIN', 'RACE_CONTROL', 'STEWARD', 'BROADCASTER', 'COMMENTATOR', 'CONTENT_CREATOR', 'LIVERY_ARTIST', 'GRAPHIC_DESIGNER', 'OTHER');

-- CreateEnum
CREATE TYPE "RealWorldRole" AS ENUM ('DRIVER', 'CO_DRIVER', 'KART_DRIVER', 'DRIVER_COACH', 'RACE_ENGINEER', 'DATA_ENGINEER', 'PERFORMANCE_ENGINEER', 'MECHANIC', 'CREW_CHIEF', 'TIRE_TECHNICIAN', 'FABRICATOR', 'TRANSPORT_LOGISTICS', 'TEAM_MANAGER', 'TEAM_OWNER', 'STRATEGIST', 'SPOTTER', 'RACE_DIRECTOR', 'STEWARD', 'MARSHAL', 'SCRUTINEER', 'TIMING_OFFICIAL', 'MEDICAL', 'SAFETY_CREW', 'COMMENTATOR', 'PHOTOGRAPHER', 'VIDEOGRAPHER', 'JOURNALIST', 'PR_COMMUNICATIONS', 'SPONSORSHIP_SALES', 'HOSPITALITY', 'OTHER');

-- AlterTable
ALTER TABLE "Profile" ADD COLUMN     "realWorldRoles" "RealWorldRole"[],
ADD COLUMN     "simRoles" "SimRole"[];

-- CreateIndex
CREATE INDEX "Profile_simRoles_idx" ON "Profile" USING GIN ("simRoles");

-- CreateIndex
CREATE INDEX "Profile_realWorldRoles_idx" ON "Profile" USING GIN ("realWorldRoles");

